-- Test data for gamespy, all data must be input in order to avoid dependence errors
BEGIN

-- Publishers
INSERT INTO publishers VALUES('', 'Activision');
INSERT INTO publishers VALUES('', 'Infinity Ward');
INSERT INTO publishers VALUES('', 'Ubisoft');
INSERT INTO publishers VALUES('', 'Naughty Dog');
INSERT INTO publishers VALUES('', 'Blizzard Entertainment');
INSERT INTO publishers VALUES('', 'EA Games');
INSERT INTO publishers VALUES('', 'Sony Online Entertainment');
INSERT INTO publishers VALUES('', 'Bungie');
INSERT INTO publishers VALUES('', 'Rockstar Games');

-- Manufacturers
INSERT INTO manufacturers VALUES('', 'Nintendo');
INSERT INTO manufacturers VALUES('', 'Sony');
INSERT INTO manufacturers VALUES('', 'Microsoft');
INSERT INTO manufacturers VALUES('', 'Atari');
INSERT INTO manufacturers VALUES('', 'Sega');

-- Game test data
INSERT INTO games VALUES('', null, 1, 'FPS', q'{Call of Duty: Advanced Warfare}', '03-NOV-14', q'{Call of Duty: Advanced Warfare. Power changes everything The power of the next generation of advanced soldier. The power of a gripping performance from Kevin Spacey. The power of all-new exoskeleton gameplay mechanics. Power changes everything. Call of Duty: Advanced Warfare delivers an inspired new era of Call of Duty. Published by Activision and developed for consoles and PC by Sledgehammer Games, Call of Duty: Advanced Warfare delivers a breath taking new vision for the blockbuster franchise, jolting players forward in a ground-breaking experience that's ripped from the headlines of tomorrow, envisioning a future where both technology and tactics have evolved to usher in a new era of combat for the franchise. Delivers a stunning vision of the future Set in the year 2054, a private military corporation (PMC) has emerged with the power to rescue humanity from a devastated world struggling to rebuild after a global attack on its military and infrastructure. You are the advanced soldier, empowered with cutting-edge exoskeleton abilities, technological advancements, and high-tech gear, players join the ranks of a highly-trained, specialised unit committed to restoring order in a state of advanced warfare. Prepare for the next-generation advanced soldier The game has been developed specifically for next-gen consoles and PC. This is the first iteration of publisher Activision's expanded three-year development cycle, allowing the debut lead title from Sledgehammer Games an added year of studio development. With the expanded production capabilities, Sledgehammer Games are able to create an astonishing next-generation experience, featuring an array of technical advancements from the sights and sounds that create a near photorealistic world unlike any Call of Duty before, to new performance capture and facial animation technologies that deliver lifelike characters, to a rich and immersive story that brings the fiction to life.}', '50.00', 'FPS, COD, Call of Duty, Game of the Year, Teenagers, 18+, Online, Shooter, Single Player, Multi Player', '9.2');
INSERT INTO games VALUES('', null, 1, 'FPS', q'{Call of Duty: Modern Warfare 3}', '08-NOV-12', q'{Call of Duty Modern Warfare 3 on the PC deliverers action packed, outstanding quality and lives up to what we have come to expect from this worldwide acclaimed game series. Armed to the teeth and knee deep in conflicts the world over, Call of Duty Modern Warfare 3 on the PC will have you feeling like you are on the frontline yourself. With a variety of challenging playing modes to tackle, you will have the option to play in single-player and cooperative modes, as well as multiplayer modes that have online functionality. Call of Duty Modern Warfare 3 on the PC packs a real punch and has enough game modes to ensure even the most hardcore gamer is hooked for months!}', '18.50', 'FPS, COD, Call of Duty, Game of the Year, Teenagers, 18+, Online, Shooter, Single Player, Multi Player', '9.0');
INSERT INTO games VALUES('', null, 8, 'FPS', 'Destiny', '09-SEP-14', q'{DESTINY From the Creators of Halo® and the company that brought you Call of Duty® In Destiny you are a Guardian of the last city on Earth, able to wield incredible power. Explore the ancient ruins of our solar system, from the red dunes of Mars to the lush jungles of Venus. Defeat Earth’s enemies. Reclaim all that we have lost. Become legend. Embark on an epic action adventure with rich cinematic storytelling where you unravel the mysteries of our universe and reclaim what we lost at the fall of our Golden Age. The next evolution of the first-person action genre that provides an unprecedented combination of storytelling, cooperative, competitive, and public gameplay, and personal activities that are all seamlessly woven into an expansive, persistent online world. Venture out alone or join up with friends. The choice is yours. Personalize and upgrade every aspect of how you look and fight with a nearly limitless combination of armor, weapons, and visual customizations. Take your upgraded character into every mode, including campaign, cooperative, social, public, and competitive multiplayer. NOTE: USB flash memory and external hard drives are not supported for the Destiny Beta, regardless of storage space. The Destiny Beta must be installed to an officially supported internal or attached Hard Drive}', '55.00', 'Customise, World, Shooter, FPS, Game, MMO, XBOX ONE, PS4, Guns, 16+', '8.6');
INSERT INTO games VALUES('', null, 8, 'FPS', 'Halo', '31-JUL-15', q'{Master Chief returns to the spotlight in this long-awaited sequel to the beloved sci-fi shooter. Under the guise of a brand new development team, Halo 4 takes the chief in a bold new direction with a fresh storyline featuring foes old and new.}', '60.00', 'Halo, XBOX ONE, Exclusive, Shooter, Online', '0.0');
INSERT INTO games VALUES('', null, 6, 'SPORT', 'FIFA 15', '23-SEP-14', q'{FIFA 15 brings football to life in stunning detail so fans can experience the emotion of the sport like never before. Witness the intensity of crowds chanting and cheering like on match day, and listen to commentators guide fans through the story of the game with Dynamic Match Presentation. For the first time ever, all 22 players on the pitch are connected with Emotional Intelligence – now players will react to opponents and teammates within the context, and relative to the narrative of the match. Next Generation Visuals put fans on Living Pitches with grass that wears and tears as the match progresses. Mud will stick to kits and Authentic Player Visuals make players lean, athletic, and true to their real-life appearance. Player Control heightens the responsiveness of player movement, gives athletes more control and personality on the ball, and makes Man-to-Man Battles more rewarding than ever before. Football is the greatest drama on earth and FIFA 15 puts fans centre stage allowing them to feel the emotion and intensity of the world’s greatest sport.}', '45.00', 'Football, Sports, EA, Fifa, Online', '8.7');
INSERT INTO games VALUES('', null, 6, 'SPORT', 'FIFA: Road to the World Cup - 2010 Edition', '27-APR-10', q'{2010 FIFA World Cup South Africa will feature all the emotion and passion of the fiercest national rivalries battling on the world's biggest stage, with all 199 national teams that took part in qualification, all 10 official stadiums to be used in South Africa and stadiums from each qualifying region. Gamers will be able to play as their home nation from qualification right through to a virtual reproduction of the FIFA World Cup Final and feel what it is like to score the goal that lifts a nation. Everything fans love about the World Cup will come to life in spectacular detail, including confetti rain, streamers, & fireworks—just like the official tournament. For the first time ever in a videogame compete in a full and authentic online World Cup tournament. Carry the hopes and dreams of a nation into battle against fans from rival countries, from the group stage through the knockout rounds to the chance to be crowned 2010 FIFA World Cup South Africa champion. For fans of nations that failed to qualify for South Africa this is the chance to replay and re-write history. Plus, gameplay innovations capture the journey from qualification to the final tournament with home and away strategies for every nation, situational tactics in-game, and altitude effects that fatigue players faster and even impact the flight of the ball.}', '8.00', 'Football, Sports, EA, Fifa, Online', '9.8');
INSERT INTO games VALUES('', null, 5, 'MMO', q'{World of Warcraft : Warlord's of Draenor}', '13-NOV-14', q'{The heroes of Azeroth are on the verge of a war that will reforge the fate of two worlds. World of Warcraft: Warlords of Draenor, the fifth expansion to Blizzard Entertainment’s acclaimed massively multiplayer online role-playing game, sends players to the world of Draenor at a pivotal moment in history to fight against and alongside legends from Warcraft’s brutal past. Across Draenor's savage jungles and battle-scarred plains, Azeroth's heroes will engage in a mythic conflict involving mystical draenei champions and mighty orc clans, and cross axes with the likes of Grommash Hellscream, Blackhand, and Ner'zhul at the height of their primal power. Players will need to scour this unwelcoming land in search of allies to help build a desperate defense against the Iron Horde’s formidable engine of conquest - or else watch their own world’s bloody, war-torn history repeat itself.}', '40.50', 'WoW, PC, Mac, World of Warcraft, New Expansion, Expansion, 2014, New Graphics', '9.5');
INSERT INTO games VALUES('', null, 7, 'MMO', 'EverQuest Next', '01-SEP-16', q'{EverQuest Next is a complete reimagining of the EverQuest Franchise. Old friends and enemies will appear — but they may not be who you remember. With 10,000 years of explorable history buried beneath its surface and a future you will shape, this is your Norrath. Everything in EverQuest Next can be destroyed. Crush the ground beneath an enemy's feet — or bury him under an avalanche you created. The world is your weapon. The land of Norrath changes every day, based on the actions of all players… including you. Cities rise and fall, kings live and die, even the gods may change. You won't want to miss a moment of it! Our character classes are streamlined and designed to be mixed. Want to be a teleporting rogue or a backstabbing barbarian? The choice is yours! Your choices will rule your destiny. Do you save a villager's burning farm or choose to do nothing? Do you clear orc camps away from Qeynos or help them destroy the city? You will make your own story — and shape the world for those who follow you. Have you ever wanted to build a game? Landmark gives you all the tools you need to design anything you can imagine. Your creations could even end up as a part of EverQuest Next.}', '50.00', 'EQN, EQ, EverQuest, Quest, MMO, MMORPG, New Game, TBA, 2016', '0.0');
INSERT INTO games VALUES('', null, 9, 'MMO', 'Grand Theft Auto V', '17-SEP-13', q'{Los Santos: a sprawling sun-soaked metropolis full of self-help gurus, starlets and fading celebrities, once the envy of the Western world, now struggling to stay afloat in an era of economic uncertainty and cheap reality TV. Amidst the turmoil, three very different criminals plot their own chances of survival and success: Franklin, a street hustler looking for real opportunities and serious money; Michael, a professional ex-con whose retirement is a lot less rosy than he hoped it would be; and Trevor, a violent maniac driven by the chance of a cheap high and the next big score. Running out of options, the crew risks everything in a series of daring and dangerous heists that could set them up for life. The biggest, most dynamic and most diverse open world ever created, Grand Theft Auto V blends storytelling and gameplay in new ways as players repeatedly jump in and out of the lives of the game’s three lead characters, playing all sides of the game’s interwoven story.}', '40.00', 'Latest GTA, New Graphics, Shooter, Single Player, multiplayer, Revolutionary', '8.6');

-- Console test data
INSERT INTO consoles VALUES('', null, 3, 'XBOX ONE', '22-NOV-13', '450.00', q'{Xbox One is a home video game console developed and marketed by Microsoft. Announced on May 21, 2013, it is the successor to the Xbox 360 and is the third console in the Xbox family. It directly competes with Sony's PlayStation 4 and Nintendo's Wii U as part of the eighth generation of video game consoles. Xbox One was released across North America, several European markets, Australia, and New Zealand on November 22, 2013, and later in 26 other markets, including Japan, the remaining European markets, and the Middle East, in September 2014. It is also the first Xbox game console to be released in China, specifically in the Shanghai Free-Trade Zone. Microsoft and various publications have classified the device as an "all-in-one entertainment system", making it a competitor to other digital media players such as the Apple TV and the Google TV platforms.}', 'XBOX, XBOX ONE, Latest XBOX, 2014');
INSERT INTO consoles VALUES('', null, 1, 'Nintendo Wii-U', '19-AUG-14', '200.00', q'{The Wii U is the first Nintendo console to support high-definition graphics. The Wii U's primary controller is the Wii U GamePad, which features an embedded touchscreen. Each software title may be designed to utilize this touchscreen as being supplemental to the main TV, or as the only screen for Off-TV Play. Each game may support any combination of the GamePad, the Wii Remote, the Wii Nunchuk, the Wii Balance Board, or Nintendo's more classically shaped Wii U Pro Controller. The system is backward compatible with Wii software; this mode also utilizes Wii-based controllers, and it optionally offers the GamePad as its primary Wii display and motion sensor bar. Nintendo features these online platforms for Wii U and 3DS: the Nintendo eShop for official software and content; and Miiverse, a social network which is dedicated to free use by Nintendo system owners and is variously integrated with games and applications.}', 'Latest Nintendo Wii, Nintendo, 2014');
INSERT INTO consoles VALUES('', null, 3, 'XBOX 360', '03-MAR-10', '200.00', q'{The Xbox 360 is a home video game console developed by Microsoft, and is the successor to the original Xbox, and it is the second console in the Xbox series. The Xbox 360 competes with Sony's PlayStation 3 and Nintendo's Wii as part of the seventh generation of video game consoles. The Xbox 360 was officially unveiled on MTV on May 12, 2005, with detailed launch and game information divulged later that month at the Electronic Entertainment Expo (E3).The Xbox 360 features an online service, Xbox Live, which was expanded from its previous iteration on the original Xbox and received regular updates during the console's lifetime. Available in free and subscription-based varieties, Xbox Live allows users to: play games online; download games (through Xbox Live Arcade) and game demos; purchase and stream music, television programs, and films through the Xbox Music and Xbox Video portals; and access third-party content services through media streaming applications. In addition to online multimedia features, the Xbox 360 allows users to stream media from local PCs. Several peripherals have been released, including wireless controllers, expanded hard drive storage, and the Kinect motion sensing camera. The release of these additional services and peripherals helped the Xbox brand grow from gaming-only to encompassing all multimedia, turning it into a hub for living-room computing entertainment.}', 'XBOX, Old Console, XBOX 360');
INSERT INTO consoles VALUES('', null, 2, 'Playstation 4', '03/JAN/2014', '420.00', q'{The PlayStation 4 (officially abbreviated as PS4) is a home video game console from Sony Computer Entertainment. Announced as the successor to the PlayStation 3 during a press conference on 20 February 2013, it was launched on 15 November 2013, in North America, and 29 November 2013, in Europe and Australia. It competes with Nintendo's Wii U and Microsoft's Xbox One, as one of the eighth generation of video game consoles. Moving away from the more complex Cell architecture of its predecessor, the PlayStation 4 features an AMD x86-64 Accelerated Processing Unit, in hopes of attracting a broader range of developers and support for the system. The PlayStation 4's GPU can perform 1.843 teraflops. Sony calls the PlayStation 4 "the world's most powerful console" and, speaking to Edge magazine, numerous game developers described the performance difference between the PS4 and Xbox One as "'significant' and 'obvious'".}', 'PS4, Latest Playstation, Playstation, 2014');
INSERT INTO consoles VALUES('', null, 3, 'PC', '11-AUG-14', '800.00', q'{A gaming computer (also gaming rig and sometimes called a gaming PC) is a personal computer designed for playing computationally demanding video games. Gaming computers are very similar to conventional PCs, with the main difference being the addition of performance-oriented components such as a high-end CPU and one or more video cards. Gaming computers are often associated with enthusiast computing due to an overlap in interests. However, while a gaming PC is built to achieve performance for actual gameplay, enthusiast PCs are built to maximize performance, using games as a benchmark. The difference between the two carries a large discrepancy in the cost of the system. Whereas enthusiast PCs are high-end by definition, gaming PCs can be subdivided into low-end, mid-range, and high-end segments. Contrary to the popular misconception that PC gaming is inextricably tied to high-priced enthusiast computing, video card manufacturers earn the bulk of their revenue from their low-end and mid-range offerings. Because of the large variety of parts that can go into a computer built to play video games, gaming computers are typically custom-made, rather than pre-assembled, either by gaming and hardware enthusiasts or by companies that specialize in producing custom gaming machines. In order to generate interest, gaming computer manufacturers that sell complete systems often produce boutique models, allowing them to compete on aesthetic design in addition to the hardware inside.}', 'PC, Home rig, Gaming desktop');


-- Stores
INSERT INTO stores VALUES('', 'Gamestop', q'{We are a local high street GAME store based in sunny Plymouths town center, just outside of the Drake Circus doors.  Please feel free to stop by and browse our wares, our stuff are always dedicated to help you find the next great game title to sink your teeth into!}', 'PL11EA', null);
INSERT INTO stores VALUES('', 'Game', q'{Why don't you stop by the Swansgate GAME store today to pick up your latest title? We sell everything from Consoles to Games, on every platform you can think of...Have you ever wanted to play any legacy Playstation 1 titles? Well we can help you there!  We have a vast array of old games sitting in our store cabanet and would be happy to sell them on to you, come see us today and our friendly staff will be happy to help.}', 'NN81EX', null);
INSERT INTO stores VALUES('', 'Game Station', q'{We are a friendly branch of the Gamestation brand, based in Exeter - we sell every type of game for any type of platform, and have an array of excellent staff to help you fulfill your gaming needs.  With years of experience and knowledge of the industry, our staff members are able to help you find the new title you wish to sink your teeth into, so what are you waiting for? Come and visit us in store today and we will be happy to help...we also have a lifetime promotional philosophy, of if you find the game or console you want for cheaper anywhere else, we will beat them drastically!}', 'EX43HP', null);
INSERT INTO stores VALUES('', 'Game Station', q'{We are a rival game store in Plymouth, come and visit us and we will undercut the prices which GAME offer by 10%, thats right 10%!  We have a 1 year guarantee on all our products, but are happy to extend that for a fair and affordable price.  Come in today and see our fantastic new deals on the XBOX ONE and Playstation 4!}', 'PL11RW', null);


-- Items
INSERT INTO items VALUES('', 1, 11, 11, '', '48.50',10);
INSERT INTO items VALUES('', 1, 11, 14, '', '55.00',2);
INSERT INTO items VALUES('', 1, 14, 11, null, 40.10,3);
INSERT INTO items VALUES('', 1, 14, 12, null, '19.50',1);
INSERT INTO items VALUES('', 1, 14, 14, null, '36.30',10);
INSERT INTO items VALUES('', 1, 14, 13, null, '28.40',12);
INSERT INTO items VALUES('', 1, 16, 15, null, '22.80',23);
INSERT INTO items VALUES('', 1, 18, 15, null, '30.80',2);
INSERT INTO items VALUES('', 1, 18, 12, null, '26.80',3);

INSERT INTO items VALUES('', 2, 11, 11, '', '48.50',10);
INSERT INTO items VALUES('', 2, 11, 14, '', '55.00',2);
INSERT INTO items VALUES('', 2, 14, 11, null, 40.10,3);
INSERT INTO items VALUES('', 2, 14, 12, null, '19.50',1);
INSERT INTO items VALUES('', 2, 14, 14, null, '36.30',10);
INSERT INTO items VALUES('', 2, 14, 13, null, '28.40',12);
INSERT INTO items VALUES('', 2, 16, 15, null, '22.80',23);
INSERT INTO items VALUES('', 1, 18, 15, null, '31.80',2);

INSERT INTO items VALUES('', 3, 11, 11, '', null,18);
INSERT INTO items VALUES('', 3, 11, 14, '', '60.00',25);
INSERT INTO items VALUES('', 3, 14, 11, null, null,8);
INSERT INTO items VALUES('', 3, 14, 12, null, '20.00',5);
INSERT INTO items VALUES('', 3, 14, 14, null, '39.00',25);
INSERT INTO items VALUES('', 3, 14, 13, null, '40.00',12);
INSERT INTO items VALUES('', 4, 16, 15, null, '32.00',12);

INSERT INTO items VALUES('', 4, 11, 11, '', '50.00',22);
INSERT INTO items VALUES('', 4, 11, 14, '', '60.00',12);
INSERT INTO items VALUES('', 4, 14, 11, null, 42.00,5);
INSERT INTO items VALUES('', 4, 14, 12, null, '18.00',7);
INSERT INTO items VALUES('', 4, 14, 14, null, '36.00',12);
INSERT INTO items VALUES('', 4, 14, 13, null, '28.00',16);
INSERT INTO items VALUES('', 4, 16, 15, null, '28.00',28);
INSERT INTO items VALUES('', 1, 18, 15, null, '26.35',2);

COMMIT;
END;